# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Mark/Desktop/review/VHDL/osci_ipc/osci_ipc.srcs/sources_1/ip/PLL_NCO/PLL_NCO.xci
# IP: The module: 'PLL_NCO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Mark/Desktop/review/VHDL/osci_ipc/osci_ipc.gen/sources_1/ip/PLL_NCO/PLL_NCO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_NCO'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Mark/Desktop/review/VHDL/osci_ipc/osci_ipc.srcs/sources_1/ip/PLL_NCO/PLL_NCO.xci
# IP: The module: 'PLL_NCO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Mark/Desktop/review/VHDL/osci_ipc/osci_ipc.gen/sources_1/ip/PLL_NCO/PLL_NCO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_NCO'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
