# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Mark/Desktop/review/VHDL/QAM_Transmitter/QAM_Transmitter.srcs/sources_1/ip/SRRC_Filter/SRRC_Filter.xci
# IP: The module: 'SRRC_Filter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Mark/Desktop/review/VHDL/QAM_Transmitter/QAM_Transmitter.gen/sources_1/ip/SRRC_Filter/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'SRRC_Filter'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Mark/Desktop/review/VHDL/QAM_Transmitter/QAM_Transmitter.gen/sources_1/ip/SRRC_Filter/SRRC_Filter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SRRC_Filter'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Mark/Desktop/review/VHDL/QAM_Transmitter/QAM_Transmitter.srcs/sources_1/ip/SRRC_Filter/SRRC_Filter.xci
# IP: The module: 'SRRC_Filter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Mark/Desktop/review/VHDL/QAM_Transmitter/QAM_Transmitter.gen/sources_1/ip/SRRC_Filter/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'SRRC_Filter'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Mark/Desktop/review/VHDL/QAM_Transmitter/QAM_Transmitter.gen/sources_1/ip/SRRC_Filter/SRRC_Filter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SRRC_Filter'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
